#pragma once

#include "engine/core/types.h"
#include <vector>
#include <string>
#include <unordered_map>
#include <mutex>

namespace nge::rhi {

// ─── GPU Subpass Input Attachment Manager ─────────────────────────────────
// Manages input attachment bindings between subpasses within a merged
// render pass. Tracks which attachments are produced by which subpass
// and consumed as inputs by subsequent subpasses, validates dependencies,
// and generates subpass dependency descriptors.
//
// Use cases:
//   - GBuffer -> Lighting subpass input attachments
//   - Deferred decal reads from previous subpass outputs
//   - Validate subpass input attachment references
//   - Generate VkSubpassDependency descriptors
//   - Track attachment lifetime across subpasses

enum class InputAttachmentType : u8 {
    Color,
    DepthStencil,
    Resolve,
};

struct SubpassAttachmentRef {
    u32                  attachmentIndex;
    InputAttachmentType  type;
    u32                  producerSubpass;   // Which subpass writes this
    u32                  consumerSubpass;   // Which subpass reads this
    std::string          debugName;
};

struct SubpassDependency {
    u32 srcSubpass;
    u32 dstSubpass;
    u32 srcStageMask;    // Pipeline stage flags (opaque)
    u32 dstStageMask;
    u32 srcAccessMask;   // Access flags (opaque)
    u32 dstAccessMask;
    bool byRegion;       // Tile-local dependency
};

struct SubpassInputConfig {
    u32  maxSubpasses = 16;
    u32  maxAttachments = 32;
    u32  maxInputsPerSubpass = 8;
    bool autoGenerateDependencies = true;
};

struct SubpassInputStats {
    u32 totalSubpasses;
    u32 totalAttachments;
    u32 totalInputRefs;
    u32 totalDependencies;
    u32 validationErrors;
    u32 byRegionDependencies;
};

class SubpassInputManager {
public:
    bool Init(const SubpassInputConfig& config = {});
    void Shutdown();

    // Declare a subpass
    bool DeclareSubpass(u32 subpassIndex, const std::string& name = "");

    // Declare an attachment written by a subpass
    bool DeclareOutput(u32 subpassIndex, u32 attachmentIndex, InputAttachmentType type,
                        const std::string& name = "");

    // Declare an input attachment read by a subpass
    bool DeclareInput(u32 consumerSubpass, u32 attachmentIndex);

    // Validate all input references (every input must have a producer)
    bool Validate() const;

    // Get validation errors
    std::vector<std::string> GetValidationErrors() const;

    // Generate subpass dependencies
    std::vector<SubpassDependency> GenerateDependencies() const;

    // Get all input attachment refs for a subpass
    std::vector<SubpassAttachmentRef> GetInputsForSubpass(u32 subpassIndex) const;

    // Get all output attachment refs for a subpass
    std::vector<SubpassAttachmentRef> GetOutputsForSubpass(u32 subpassIndex) const;

    // Get the producer subpass for an attachment
    u32 GetProducer(u32 attachmentIndex) const;

    // Get all consumers of an attachment
    std::vector<u32> GetConsumers(u32 attachmentIndex) const;

    // Check if an attachment is used as input in any subpass
    bool IsInputAttachment(u32 attachmentIndex) const;

    u32 GetSubpassCount() const;
    u32 GetAttachmentCount() const;

    void Reset();

    SubpassInputStats GetStats() const;

private:
    SubpassInputConfig m_config;

    struct SubpassInfo {
        u32 index;
        std::string name;
        std::vector<u32> outputAttachments;
        std::vector<u32> inputAttachments;
    };

    struct AttachmentInfo {
        u32 index;
        InputAttachmentType type;
        u32 producerSubpass;
        std::vector<u32> consumerSubpasses;
        std::string debugName;
    };

    std::unordered_map<u32, SubpassInfo> m_subpasses;
    std::unordered_map<u32, AttachmentInfo> m_attachments;

    mutable u32 m_validationErrors = 0;
    mutable std::mutex m_mutex;
};

} // namespace nge::rhi
