#include "engine/rhi/common/rhi_subpass_input_manager.h"
#include "engine/core/logging/log.h"
#include <algorithm>

namespace nge::rhi {

bool SubpassInputManager::Init(const SubpassInputConfig& config) {
    m_config = config;
    m_validationErrors = 0;

    NGE_LOG_INFO("Subpass input manager initialized: maxSubpasses={}, maxAttachments={}, maxInputs={}, autoDeps={}",
                 config.maxSubpasses, config.maxAttachments, config.maxInputsPerSubpass, config.autoGenerateDependencies);
    return true;
}

void SubpassInputManager::Shutdown() {
    m_subpasses.clear();
    m_attachments.clear();
}

bool SubpassInputManager::DeclareSubpass(u32 subpassIndex, const std::string& name) {
    std::lock_guard lock(m_mutex);

    if (m_subpasses.size() >= m_config.maxSubpasses && m_subpasses.find(subpassIndex) == m_subpasses.end()) {
        NGE_LOG_ERROR("Subpass input: max subpasses reached ({})", m_config.maxSubpasses);
        return false;
    }

    if (m_subpasses.find(subpassIndex) == m_subpasses.end()) {
        SubpassInfo info;
        info.index = subpassIndex;
        info.name = name;
        m_subpasses[subpassIndex] = std::move(info);
    }

    return true;
}

bool SubpassInputManager::DeclareOutput(u32 subpassIndex, u32 attachmentIndex, InputAttachmentType type,
                                          const std::string& name) {
    std::lock_guard lock(m_mutex);

    if (m_subpasses.find(subpassIndex) == m_subpasses.end()) {
        NGE_LOG_WARN("Subpass input: subpass {} not declared", subpassIndex);
        return false;
    }

    if (m_attachments.size() >= m_config.maxAttachments && m_attachments.find(attachmentIndex) == m_attachments.end()) {
        NGE_LOG_ERROR("Subpass input: max attachments reached ({})", m_config.maxAttachments);
        return false;
    }

    // Register attachment
    AttachmentInfo& att = m_attachments[attachmentIndex];
    att.index = attachmentIndex;
    att.type = type;
    att.producerSubpass = subpassIndex;
    att.debugName = name;

    // Add to subpass outputs
    auto& outputs = m_subpasses[subpassIndex].outputAttachments;
    if (std::find(outputs.begin(), outputs.end(), attachmentIndex) == outputs.end()) {
        outputs.push_back(attachmentIndex);
    }

    return true;
}

bool SubpassInputManager::DeclareInput(u32 consumerSubpass, u32 attachmentIndex) {
    std::lock_guard lock(m_mutex);

    if (m_subpasses.find(consumerSubpass) == m_subpasses.end()) {
        NGE_LOG_WARN("Subpass input: consumer subpass {} not declared", consumerSubpass);
        return false;
    }

    auto& inputs = m_subpasses[consumerSubpass].inputAttachments;
    if (inputs.size() >= m_config.maxInputsPerSubpass) {
        NGE_LOG_WARN("Subpass input: max inputs per subpass reached ({})", m_config.maxInputsPerSubpass);
        return false;
    }

    if (std::find(inputs.begin(), inputs.end(), attachmentIndex) == inputs.end()) {
        inputs.push_back(attachmentIndex);
    }

    // Register consumer
    if (m_attachments.find(attachmentIndex) != m_attachments.end()) {
        auto& consumers = m_attachments[attachmentIndex].consumerSubpasses;
        if (std::find(consumers.begin(), consumers.end(), consumerSubpass) == consumers.end()) {
            consumers.push_back(consumerSubpass);
        }
    }

    return true;
}

bool SubpassInputManager::Validate() const {
    std::lock_guard lock(m_mutex);

    m_validationErrors = 0;
    bool valid = true;

    // Check every input has a producer
    for (const auto& [spIdx, sp] : m_subpasses) {
        for (u32 inputAtt : sp.inputAttachments) {
            auto it = m_attachments.find(inputAtt);
            if (it == m_attachments.end()) {
                m_validationErrors++;
                valid = false;
                continue;
            }

            // Producer must be an earlier subpass
            if (it->second.producerSubpass >= spIdx) {
                m_validationErrors++;
                valid = false;
            }
        }
    }

    return valid;
}

std::vector<std::string> SubpassInputManager::GetValidationErrors() const {
    std::lock_guard lock(m_mutex);

    std::vector<std::string> errors;

    for (const auto& [spIdx, sp] : m_subpasses) {
        for (u32 inputAtt : sp.inputAttachments) {
            auto it = m_attachments.find(inputAtt);
            if (it == m_attachments.end()) {
                errors.push_back("Subpass " + std::to_string(spIdx) +
                                  " reads attachment " + std::to_string(inputAtt) +
                                  " which has no producer");
            } else if (it->second.producerSubpass >= spIdx) {
                errors.push_back("Subpass " + std::to_string(spIdx) +
                                  " reads attachment " + std::to_string(inputAtt) +
                                  " produced by later subpass " + std::to_string(it->second.producerSubpass));
            }
        }
    }

    return errors;
}

std::vector<SubpassDependency> SubpassInputManager::GenerateDependencies() const {
    std::lock_guard lock(m_mutex);

    std::vector<SubpassDependency> deps;

    for (const auto& [attIdx, att] : m_attachments) {
        for (u32 consumer : att.consumerSubpasses) {
            SubpassDependency dep;
            dep.srcSubpass = att.producerSubpass;
            dep.dstSubpass = consumer;

            // Color attachment output -> fragment shader input
            if (att.type == InputAttachmentType::Color) {
                dep.srcStageMask = 0x00000400; // COLOR_ATTACHMENT_OUTPUT
                dep.dstStageMask = 0x00000080; // FRAGMENT_SHADER
                dep.srcAccessMask = 0x00000100; // COLOR_ATTACHMENT_WRITE
                dep.dstAccessMask = 0x00000010; // INPUT_ATTACHMENT_READ
            } else if (att.type == InputAttachmentType::DepthStencil) {
                dep.srcStageMask = 0x00000200; // LATE_FRAGMENT_TESTS
                dep.dstStageMask = 0x00000080; // FRAGMENT_SHADER
                dep.srcAccessMask = 0x00000400; // DEPTH_STENCIL_WRITE
                dep.dstAccessMask = 0x00000010; // INPUT_ATTACHMENT_READ
            } else {
                dep.srcStageMask = 0x00000400;
                dep.dstStageMask = 0x00000080;
                dep.srcAccessMask = 0x00000100;
                dep.dstAccessMask = 0x00000010;
            }

            dep.byRegion = true; // Tile-local for subpass dependencies

            deps.push_back(dep);
        }
    }

    return deps;
}

std::vector<SubpassAttachmentRef> SubpassInputManager::GetInputsForSubpass(u32 subpassIndex) const {
    std::lock_guard lock(m_mutex);

    std::vector<SubpassAttachmentRef> refs;

    auto spIt = m_subpasses.find(subpassIndex);
    if (spIt == m_subpasses.end()) return refs;

    for (u32 attIdx : spIt->second.inputAttachments) {
        auto attIt = m_attachments.find(attIdx);
        if (attIt == m_attachments.end()) continue;

        SubpassAttachmentRef ref;
        ref.attachmentIndex = attIdx;
        ref.type = attIt->second.type;
        ref.producerSubpass = attIt->second.producerSubpass;
        ref.consumerSubpass = subpassIndex;
        ref.debugName = attIt->second.debugName;
        refs.push_back(ref);
    }

    return refs;
}

std::vector<SubpassAttachmentRef> SubpassInputManager::GetOutputsForSubpass(u32 subpassIndex) const {
    std::lock_guard lock(m_mutex);

    std::vector<SubpassAttachmentRef> refs;

    auto spIt = m_subpasses.find(subpassIndex);
    if (spIt == m_subpasses.end()) return refs;

    for (u32 attIdx : spIt->second.outputAttachments) {
        auto attIt = m_attachments.find(attIdx);
        if (attIt == m_attachments.end()) continue;

        SubpassAttachmentRef ref;
        ref.attachmentIndex = attIdx;
        ref.type = attIt->second.type;
        ref.producerSubpass = subpassIndex;
        ref.consumerSubpass = UINT32_MAX;
        ref.debugName = attIt->second.debugName;
        refs.push_back(ref);
    }

    return refs;
}

u32 SubpassInputManager::GetProducer(u32 attachmentIndex) const {
    std::lock_guard lock(m_mutex);

    auto it = m_attachments.find(attachmentIndex);
    if (it == m_attachments.end()) return UINT32_MAX;

    return it->second.producerSubpass;
}

std::vector<u32> SubpassInputManager::GetConsumers(u32 attachmentIndex) const {
    std::lock_guard lock(m_mutex);

    auto it = m_attachments.find(attachmentIndex);
    if (it == m_attachments.end()) return {};

    return it->second.consumerSubpasses;
}

bool SubpassInputManager::IsInputAttachment(u32 attachmentIndex) const {
    std::lock_guard lock(m_mutex);

    auto it = m_attachments.find(attachmentIndex);
    if (it == m_attachments.end()) return false;

    return !it->second.consumerSubpasses.empty();
}

u32 SubpassInputManager::GetSubpassCount() const {
    std::lock_guard lock(m_mutex);
    return static_cast<u32>(m_subpasses.size());
}

u32 SubpassInputManager::GetAttachmentCount() const {
    std::lock_guard lock(m_mutex);
    return static_cast<u32>(m_attachments.size());
}

void SubpassInputManager::Reset() {
    std::lock_guard lock(m_mutex);
    m_subpasses.clear();
    m_attachments.clear();
    m_validationErrors = 0;
}

SubpassInputStats SubpassInputManager::GetStats() const {
    std::lock_guard lock(m_mutex);

    SubpassInputStats stats{};
    stats.totalSubpasses = static_cast<u32>(m_subpasses.size());
    stats.totalAttachments = static_cast<u32>(m_attachments.size());

    u32 inputRefs = 0;
    for (const auto& [idx, sp] : m_subpasses) {
        inputRefs += static_cast<u32>(sp.inputAttachments.size());
    }
    stats.totalInputRefs = inputRefs;

    // Count dependencies
    u32 depCount = 0;
    u32 byRegion = 0;
    for (const auto& [attIdx, att] : m_attachments) {
        depCount += static_cast<u32>(att.consumerSubpasses.size());
        byRegion += static_cast<u32>(att.consumerSubpasses.size()); // All are by-region
    }
    stats.totalDependencies = depCount;
    stats.byRegionDependencies = byRegion;
    stats.validationErrors = m_validationErrors;

    return stats;
}

} // namespace nge::rhi
