// ─── Ocean / Water Rendering Shader ───────────────────────────────────────
// GPU-driven ocean surface using FFT-based wave simulation.
// Combines multiple octaves of Gerstner waves with a displacement map
// generated by an inverse FFT (Tessendorf method).
//
// Pipeline:
//   1. Spectrum generation (Phillips/JONSWAP)
//   2. iFFT wave displacement (H(k,t) → height + displacement)
//   3. Normal map computation from displacement gradients
//   4. Surface shading (Fresnel, subsurface scattering, foam, reflections)

#include "../common/math.hlsl"

// ─── Constants ───────────────────────────────────────────────────────────

struct OceanConstants {
    float4x4 viewProj;
    float4x4 invViewProj;
    float4   cameraPos;
    float4   sunDirection;
    float4   sunColor;
    float4   oceanColor;          // Base deep water color
    float4   shallowColor;        // Shallow water color (coastal)
    float    time;
    float    windSpeed;
    float2   windDirection;
    float    choppiness;          // Displacement XZ scale
    float    foamThreshold;       // Jacobian threshold for foam
    float    foamIntensity;
    float    sssFactor;           // Subsurface scattering factor
    uint2    fftResolution;       // e.g., 256×256
    float    patchSize;           // World-space size of one FFT patch
    float    pad;
};

[[vk::push_constant]] ConstantBuffer<OceanConstants> pc;

// ─── Textures ────────────────────────────────────────────────────────────

Texture2D<float4> g_DisplacementMap : register(t0, space32); // xyz = displacement, w = foam
Texture2D<float4> g_NormalMap       : register(t1, space32); // xy = normal xz, z = jacobian, w = foam mask
Texture2D<float4> g_SceneColor     : register(t2, space32);
Texture2D<float>  g_DepthBuffer    : register(t3, space32);
TextureCube<float4> g_EnvironmentMap : register(t4, space32);

SamplerState g_LinearWrap  : register(s0, space32);
SamplerState g_LinearClamp : register(s1, space32);

// ─── Gerstner Wave (Analytical Fallback) ─────────────────────────────────

struct GerstnerWave {
    float2 direction;
    float  amplitude;
    float  frequency;
    float  speed;
    float  steepness;
};

float3 EvaluateGerstner(float2 worldXZ, float time, GerstnerWave wave) {
    float k = wave.frequency;
    float2 d = normalize(wave.direction);
    float phase = dot(d, worldXZ) * k - time * wave.speed;

    float3 displacement;
    displacement.x = wave.steepness * wave.amplitude * d.x * cos(phase);
    displacement.z = wave.steepness * wave.amplitude * d.y * cos(phase);
    displacement.y = wave.amplitude * sin(phase);
    return displacement;
}

// ─── Surface Shading ─────────────────────────────────────────────────────

struct OceanSurface {
    float3 position;
    float3 normal;
    float  foam;
    float  depth; // Water depth (scene depth - ocean depth)
};

float SchlickFresnel(float cosTheta, float f0) {
    return f0 + (1.0 - f0) * pow(1.0 - saturate(cosTheta), 5.0);
}

float3 ShadeOcean(OceanSurface surface, float3 viewDir) {
    float3 N = normalize(surface.normal);
    float3 V = normalize(viewDir);
    float3 L = normalize(-pc.sunDirection.xyz);
    float3 H = normalize(V + L);

    float NdotV = max(dot(N, V), 0.001);
    float NdotL = max(dot(N, L), 0.0);
    float NdotH = max(dot(N, H), 0.0);

    // Fresnel
    float fresnel = SchlickFresnel(NdotV, 0.02); // Water F0 ≈ 0.02

    // Specular (GGX-like)
    float roughness = 0.05; // Very smooth water
    float alpha = roughness * roughness;
    float denom = NdotH * NdotH * (alpha - 1.0) + 1.0;
    float D = alpha / (PI * denom * denom);
    float3 specular = pc.sunColor.rgb * D * fresnel * NdotL;

    // Reflection
    float3 R = reflect(-V, N);
    float3 envColor = g_EnvironmentMap.SampleLevel(g_LinearClamp, R, roughness * 8.0).rgb;
    float3 reflection = envColor * fresnel;

    // Subsurface scattering (light passing through thin water)
    float sss = pow(saturate(dot(V, -L)), 4.0) * pc.sssFactor;
    float3 subsurface = pc.shallowColor.rgb * sss;

    // Color based on viewing angle (deep vs shallow)
    float depthFade = saturate(surface.depth * 0.1);
    float3 waterColor = lerp(pc.shallowColor.rgb, pc.oceanColor.rgb, depthFade);

    // Combine
    float3 diffuse = waterColor * (1.0 - fresnel) * (NdotL * 0.5 + 0.5);
    float3 color = diffuse + reflection + specular + subsurface;

    // Foam
    if (surface.foam > 0.0) {
        float3 foamColor = float3(0.9, 0.95, 1.0);
        color = lerp(color, foamColor, surface.foam * pc.foamIntensity);
    }

    return color;
}

// ─── Vertex Shader (Ocean Mesh) ──────────────────────────────────────────

struct VSInput {
    float2 gridPos : POSITION; // [0,1] grid position within patch
    uint   instanceId : SV_InstanceID;
};

struct VSOutput {
    float4 clipPos   : SV_Position;
    float3 worldPos  : TEXCOORD0;
    float2 uv        : TEXCOORD1;
    float3 normal    : TEXCOORD2;
    float  foam      : TEXCOORD3;
};

VSOutput VSMain(VSInput input) {
    VSOutput output;

    // Grid to world position
    float2 worldXZ = (input.gridPos - 0.5) * pc.patchSize;

    // Sample displacement from FFT result
    float2 uv = input.gridPos;
    float4 displacement = g_DisplacementMap.SampleLevel(g_LinearWrap, uv, 0);
    float4 normalData = g_NormalMap.SampleLevel(g_LinearWrap, uv, 0);

    float3 worldPos;
    worldPos.x = worldXZ.x + displacement.x * pc.choppiness;
    worldPos.y = displacement.y;
    worldPos.z = worldXZ.y + displacement.z * pc.choppiness;

    output.worldPos = worldPos;
    output.clipPos = mul(pc.viewProj, float4(worldPos, 1.0));
    output.uv = uv;
    output.normal = normalize(float3(normalData.x, 1.0, normalData.y));
    output.foam = saturate(normalData.w);

    return output;
}

// ─── Pixel Shader ────────────────────────────────────────────────────────

float4 PSMain(VSOutput input) : SV_Target0 {
    float3 viewDir = pc.cameraPos.xyz - input.worldPos;
    float viewDist = length(viewDir);

    OceanSurface surface;
    surface.position = input.worldPos;
    surface.normal = input.normal;
    surface.foam = input.foam;
    surface.depth = 5.0; // TODO: Compute from scene depth buffer

    float3 color = ShadeOcean(surface, viewDir);

    // Distance fog blending
    float fogFactor = 1.0 - exp(-viewDist * 0.0005);
    float3 fogColor = float3(0.6, 0.7, 0.8);
    color = lerp(color, fogColor, fogFactor);

    return float4(color, 0.9); // Slight transparency for shallow water edges
}

// ─── Spectrum Generation (Compute) ───────────────────────────────────────

RWTexture2D<float4> g_Spectrum : register(u0, space32);

float Phillips(float2 k, float2 windDir, float windSpeed) {
    float kLen = length(k);
    if (kLen < 0.0001) return 0.0;

    float L = windSpeed * windSpeed / 9.81;
    float kDotW = dot(normalize(k), windDir);
    float phillips = exp(-1.0 / (kLen * kLen * L * L)) / (kLen * kLen * kLen * kLen);
    phillips *= kDotW * kDotW; // Directional spread

    // Suppress waves perpendicular to wind
    float dampening = 0.001;
    phillips *= exp(-kLen * kLen * dampening * dampening);

    return phillips;
}

[numthreads(8, 8, 1)]
void CSSpectrum(uint3 DTid : SV_DispatchThreadID) {
    if (DTid.x >= pc.fftResolution.x || DTid.y >= pc.fftResolution.y) return;

    float2 k = float2(DTid.xy) - float2(pc.fftResolution) * 0.5;
    k *= 2.0 * PI / pc.patchSize;

    float2 windDir = normalize(pc.windDirection);
    float spectrum = sqrt(Phillips(k, windDir, pc.windSpeed));

    // Random phase from hash (pseudo-random per pixel, deterministic)
    float hash = frac(sin(dot(float2(DTid.xy), float2(127.1, 311.7))) * 43758.5453);
    float phase = hash * 2.0 * PI;

    float2 h0 = spectrum * float2(cos(phase), sin(phase)) * 0.70710678; // 1/sqrt(2)

    g_Spectrum[DTid.xy] = float4(h0, 0, 0);
}
